#!/bin/bash

# released under Creative Commons Attribution-ShareAlike 3.0
# http://creativecommons.org/licenses/by-sa/3.0/
# v1.0
# 11. 2. 2012
# dependencies: gifsicle

sflag=

while getopts s: name
do
    case $name in
    s)    s=1
          sval="$OPTARG"
          sflag="set";;
    *)   printf "Usage: [-s seconds]\n" $0
          exit 2;;
    esac
done

if [ ! -d ~/.recorder-temp ]; then
	mkdir ~/.recorder-temp
fi
if [ -z "$sflag" ]; then
    sval=5
fi
seconds=$(echo "$sval"*10|bc)
cd ~/.recorder-temp
for (( i=1; i<=$seconds; i++ ))
do
   padi=$(printf "%04d" $i)
   screencapture -C -t "gif" "recorderframe""$padi"".gif"
   sleep .1
done
framelist=$(frames=$(ls|grep -a recorderframe);echo ${frames//\n/ })
named=$(date -j +"%Y-%m-%d")
namet=$(tim=$(date -j +"%r");echo ${tim//:/.})
filename=$(echo "Screen shot ""$named"" at ""$namet"".gif")
gifsicle -w --delay 10 --loopcount $framelist > "$filename"
gifsicle -w -b --optimize=2 "$filename"
mv "$filename" ~/Desktop/
rm recorderframe*
echo "Screen recording saved to ~/Desktop/ ."